### ISSUE TITLE
Energy refill from 0 weird implementation.

### ISSUE THREAD

**Issue by rnoriega31** [rnoriega31/TBARPG#23]
Currently, if the player energy is <= 0, the time it takes to start refilling energy will be longer than usual. The problem is that Energy can't go below 0 in the first place since actions won't even execute if not enough Energy is available, so this "punishment" will only activate if the player has exactly the same amount that executing the ability costs, which I don't see happening too often.

It would feel weird to punish players for such inconsistent reason so I propose to either remove this functionality entirely to avoid confusion or to let players go below 0 Energy ONCE: players would be able to use any ability regardless of how much energy is left but if it goes below 0 the cooldown until refill would be longer and the energy would start to refill from whatever negative value it was left off at.
While I like this in principle I feel it's a bit too obtuse for the player to know for sure if the action will leave them in a negative value.

Thoughts @ericdsw ?

**Comment by ericdsw** [comment]
An option could be like the one in Kingdom Hearts, where as long as you have energy, you can execute the ability. If you have less than the required amount of energy, all remaining energy is spent and `current_energy` will be set to zero (and it will have a delay before it starts refilling again).

This gives the following advantages:
- The player always has a reliable way to know when their energy is gonna run out, so he/she can plan accordingly.
- There is a sort of "punishment" when players use their energy too recklessly, forcing them to plan better and create new strategies (like "frame-perfect" phasing to spend as little energy as possible).
- This implementation fixes the behavior of actions that "drain" the player's energy continuously rather than those that have a fixed cost and cooldown (such is the case of phasing). If no cooldown is implemented, players can theoretically spam the ability as soon as the energy bar fills to the ability's **cost_per_tick**, creating a potentially game breaking exploit.

**Comment by ericdsw** [comment]
Implementation is as follows:
- When energy reaches 0 there is a 2 second cooldown before it starts to refill.

**Comment by ericdsw** [comment]
Possible optimized implementation:
- Energy bar will flash red while it's cooldown is active
- As long as there is energy left, the player can perform an action (even if there is less energy than the cost), but it will trigger the cooldown.
